language: python
dist: trusty
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
addons:
  apt:
    packages:
      - libspatialite-dev
install:
  - python setup.py install
# command to run tests
script: py.test -v
