language: python
python:
  - 2.7
# command to install dependencies
before_install:
  - sudo apt-get install -qq libspatialite-dev
install:
  - python setup.py install
# command to run tests
script: py.test -v
