language: python
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
      - libspatialite-dev
dist: trusty
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - python setup.py install
# command to run tests
script: py.test -v
