language: python
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
      - libspatialite-dev
dist: trusty
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
addons:
  postgresql: "9.3"
  apt:
      packages:
        - postgresql-9.3-postgis-2.3
install:
  - pip install -i https://pypi.pacificclimate.org/simple -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install .
# command to run tests
script: py.test -v
