@Library('pcic-pipeline-library')_


node {
    stage('Code Collection') {
        collectCode()
    }

    stage('Testing') {
        def requirements = ['requirements.txt', 'test_requirements.txt']
        def pytestArgs = '-v'
        def options =  [containerData: 'crmprtd']

        parallel "Python 3.6": {
            runPythonTestSuite('pcic/modelmeta-test-env:python-3.6',
                               requirements, pytestArgs, options)
        },
        "Python 3.7": {
            runPythonTestSuite('pcic/modelmeta-test-env:python-3.7',
                               requirements, pytestArgs, options)
        }
    }

    if (isPypiPublishable()) {
        stage('Push to PYPI') {
            publishPythonPackage('pcic/modelmeta-test-env:python-3.6',
                                 'PCIC_PYPI_CREDS')
        }
    }

    stage('Clean Workspace') {
        cleanWs()
    }
}
